# Generated by Django 2.0 on 2018-01-03 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_article'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(default='/home/collins/Downloads/jl.jpg', upload_to='articles/'),
        ),
    ]
