# Generated by Django 2.0 on 2018-01-23 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20180110_2146'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Editor',
        ),
    ]
