# Generated by Django 2.0 on 2018-01-23 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0009_delete_editor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('github', models.CharField(max_length=100)),
                ('live_url', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='articles/')),
            ],
        ),
    ]
