# Generated by Django 2.0 on 2018-01-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterrecipient',
            name='text',
            field=models.CharField(default='hello', max_length=200),
        ),
    ]
