# Generated by Django 2.0 on 2018-01-25 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_newsletterrecipient_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletterrecipient',
            name='text',
        ),
    ]
