# Generated by Django 2.0 on 2018-01-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_remove_newsletterrecipient_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterrecipient',
            name='text',
            field=models.CharField(default='Hello my friend', max_length=200),
        ),
    ]
