# Generated by Django 2.0 on 2018-02-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0013_newsletterrecipient_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='first_image',
        ),
        migrations.AddField(
            model_name='project',
            name='second_image',
            field=models.ImageField(blank=True, upload_to='articles/'),
        ),
    ]
